#!/usr/bin/env bash
# Task 9
cleanup_and_exit() {
    sudo rm -f /var/run/myscript.pid
    exit
}

sudo bash -c "echo $ > /var/run/myscript.pid"

trap 'echo "I hate the kill command"; cleanup_and_exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup_and_exit' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
